apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ds-admission-webhook-crt
  namespace: default
spec:
  # Secret names are always required.
  secretName: ds-admission-webhook-crt-secret
  duration: 87600h # 10 years
  renewBefore: 78840h # 9 years
  subject:
    organizations:
    - ds
  isCA: true
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    # - client auth
    - digital signature
    - key encipherment
  dnsNames:
    - ds-admission-webhook
    - ds-admission-webhook.default
    - ds-admission-webhook.default.svc
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
