apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    ds-admission-webhook/autoSchedule: "enabled"
    ds-admission-webhook/spotWeight: "99"
spec:
  replicas: 20
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        ds-admission-webhook/autoSchedule: "enabled"
        ds-admission-webhook/spotWeight: "99"
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80