apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ds-admission-webhook
  name: ds-admission-webhook
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ds-admission-webhook
  template:
    metadata:
      labels:
        app: ds-admission-webhook
        ds-admission-webhook/autoSchedule: disabled
    spec:
      serviceAccountName: webhook-service-account
      containers:
        - name: distributed-scheduling-webhook
          image: k3d-myregistry.localhost:12345/distributed-scheduling-webhook:latest
          command: [ "/node" ]
          ports:
            - containerPort: 8443
              name: webhook-api
          args:
            - -v=4
            - -log_dir=log -alsologtostderr
          volumeMounts:
            - name: ds-admission-webhook
              mountPath: /certs
            - name: kubeconfig
              mountPath: /etc/config
          resources:
            limits:
              cpu: "200m"
              memory: 100Mi
            requests:
              cpu: "200m"
              memory: 100Mi
      volumes:
        - name: ds-admission-webhook
          secret:
            secretName: ds-admission-webhook-crt-secret
        - name: kubeconfig
          configMap:
            name: kubeconfig

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ds-admission-webhook
  name: ds-admission-webhook
  namespace: default
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app: ds-admission-webhook
