apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ds-admission-webhook
  name: ds-admission-webhook
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ds-admission-webhook
  template:
    metadata:
      labels:
        app: ds-admission-webhook
        ds-admission-webhook/autoSchedule: disabled
    spec:
      containers:
        - image: webhook-test:0.0.1
          name: ds-admission-webhook
          env:
            - name: NODE_ENV
              value: production
          volumeMounts:
            - name: ds-admission-webhook
              mountPath: /certs
            - name: kubeconfig
              mountPath: /etc/config
          resources:
            limits:
              cpu: "200m"
              memory: 100Mi
            requests:
              cpu: "200m"
              memory: 100Mi
      volumes:
        - name: ds-admission-webhook
          secret:
            secretName: ds-admission-webhook-crt-secret
        - name: kubeconfig
          configMap:
            name: kubeconfig

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ds-admission-webhook
  name: ds-admission-webhook
  namespace: default
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app: ds-admission-webhook
