apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: ds-admission-webhook
  annotations:
    cert-manager.io/inject-ca-from: default/ds-admission-webhook-crt
webhooks:
  - name: ds-admission-webhook
    admissionReviewVersions: ["v1"]
    timeoutSeconds: 2
    sideEffects: "None"
    failurePolicy: "Fail"
    reinvocationPolicy: "Never"
    matchPolicy: Equivalent
    objectSelector:
      matchExpressions:
        - key: ds-admission-webhook/autoSchedule
          operator: NotIn
          values:
            - "disabled"
    namespaceSelector:
      matchExpressions:
        - key: ds-admission-webhook/autoSchedule
          operator: NotIn
          values:
            - "disabled"
    rules:
      - operations: ["CREATE"]
        apiGroups: ["apps"]
        apiVersions: ["v1"]
        resources: ["deployments", "statefulsets"]
        scope: "Namespaced"
    clientConfig:
      service:
        namespace: "default"
        name: "ds-admission-webhook"
        path: "/webhook"
        port: 443
